### ISSUE TITLE
Cumulus template should be a git submodule 

### ISSUE THREAD

**Issue by amarouane-ABDELHAK** [asfadmin/CIRRUS-core#11]
Allow the users to trace back the changes to the original authors of the source code.

**Comment by kbeamnsidc** [comment]
If I understand what you're suggesting, are you referring to the [cumulus-template-deploy](https://github.com/nasa/cumulus-template-deploy) repo? If so, I'm interpreting this to mean that you would like this repo to pull in the template as a git submodule and then...what do we do with it?
