### ISSUE TITLE
The subnets returned by the data source is not the one we want to use. 

### ISSUE THREAD

**Issue by amarouane-ABDELHAK** [asfadmin/CIRRUS-core#12]
In one account the subnet returned was the correct one but in another account it was wrong (it was the subnet id of owned resources)

**Comment by kbeamnsidc** [comment]
Should we use both subnets? I originally thought so and created Issue #7 for that. If we should only use one of them, do you happen to know if there's a Tag on that subnet that we can use to query for the correct one?

**Comment by kbeamnsidc** [comment]
From Chris Durbin:

```
data "aws_vpc" "app" {
  filter {
    name   = "tag:Name"
    values = ["Application VPC"]
  }
}
data "aws_subnet_ids" "app" {
  vpc_id = data.aws_vpc.app.id
  tags = {
    Name = "Private application *"
  }
}```
