### ISSUE TITLE
setup_jwt_cookie.sh fails

### ISSUE THREAD

**Issue by Jkovarik** [asfadmin/CIRRUS-core#162]
# Issue: container-shell make stage fails in the current container specified in the Dockerfile. 

This is failing as ssh-keygen is returning the following error: 

```
No user exists for uid 502
```

# Example:
```bash
bash-4.2:/CIRRUS-core$ source setup_jwt_cookie.sh some_daac jk dev
<removed echo-back for security reasons>
No user exists for uid 502
```

# Replication steps: 

1) `make image`
2)  make container-shell, and run the specified command from the docs (setup_jwt_cookie.sh), or directly invoke the portion of the script that is failing

**Comment by lindsleycj** [comment]
resolved in PR #164
