### ISSUE TITLE
upper-case Maturities like this fail

### ISSUE THREAD

**Issue by bbuechler** [asfadmin/CIRRUS-core#66]
https://github.com/asfadmin/CIRRUS-core/blob/7ea85d7fe8321a81154c0c52cc1dfd3990431425/jenkins/Jenkinsfile#L3

It tries to create state buckets with UC characters and fails! Also needs to be bumped in CIRRUS-DAAC: https://github.com/asfadmin/CIRRUS-DAAC/blob/master/jenkins/Jenkinsfile#L3

**Comment by mckadesorensen** [comment]
It appears that this issue has been fixed. https://github.com/asfadmin/CIRRUS-core/blob/4a8cbfa25740de316663b04e8df34e5a1e48321c/jenkins/Jenkinsfile#L3

**Comment by mckadesorensen** [comment]
It appears that this issue has been fixed.  https://github.com/asfadmin/CIRRUS-core/blob/4a8cbfa25740de316663b04e8df34e5a1e48321c/jenkins/Jenkinsfile#L3
